### ISSUE TITLE
error 035: argument type mismatch (argument 4)

### ISSUE THREAD

**Issue by CantBeKarma** [Open-GTO/mdialog#11]
Compiler Output on latest release:
> \include\mdialog.inc(408) : error 035: argument type mismatch (argument 4)
> \include\mdialog.inc(413) : error 035: argument type mismatch (argument 4)

Related Lines:

```
static stock _Dialog_Open(playerid, const function[], style, const caption[], const info[], const button1[], const button2[])
{
	gIsDialogOpen{playerid} = true;
	gDialogFunction[playerid] = !"dre_";
	strcat(gDialogFunction[playerid], function, sizeof(gDialogFunction[]));

	switch (style) {
		case DIALOG_STYLE_MSGBOX, DIALOG_STYLE_INPUT, DIALOG_STYLE_PASSWORD: {
			#if defined MDIALOG_DISABLE_TAGS
				return ShowPlayerDialog(playerid, MDIALOG_DIALOG_ID, style, caption, info, button1, button2);
			#else
				static info_result[MDIALOG_MAX_INFO_SIZE];
				_MDialog_ProcessTags(info, info_result);
				return ShowPlayerDialog(playerid, MDIALOG_DIALOG_ID, style, caption, info_result, button1, button2); // This is line 403.
			#endif
		}
	}

	return ShowPlayerDialog(playerid, MDIALOG_DIALOG_ID, style, caption, info, button1, button2); // This is line 413.
}
```

These errors don't occur when the variables via the parameter isn't "const", yet, it's obviously like that to satisfy the latest compiler version released with the whole "const-correctness" ordeal. But, it seems impossible to satisfy the compiler regardless because it gives errors such as the ones above. Any thoughts?

**Comment by ziggi** [comment]
Do you have `fixes.inc`?

**Comment by CantBeKarma** [comment]
Ah yes, fixes.inc was the cause of this issue. Thanks!

**Comment by ziggi** [comment]
But this should works with `fixes.inc`, you are using default configuration or you have disabled some `fixes` parts?

**Comment by CantBeKarma** [comment]
These are my defines prior to including _fixes.inc_:

```
#define FIXES_ServerVarMsg 0
#define FIXES_Single 1 
#include <fixes> // Community patches for buggy SA:MP functions.
```

**Comment by ziggi** [comment]
You are using v1.3.5?

**Comment by CantBeKarma** [comment]
Yeah, as well as the latest fixes include.

**Comment by ziggi** [comment]
Is `#include <fixes>` is above than `#include <mdialog>`?

**Comment by CantBeKarma** [comment]
Yup.
