### ISSUE TITLE
Why isn't the text in the middle?

### ISSUE THREAD

**Issue by Pedrilkov** [Open-GTO/mdialog#20]
My code:
```
Dialog_Open(playerid, Dialog:Auth, DIALOG_STYLE_MSGBOX, "Ошибка", "\\cНеверный пароль", "Ок", "");
```
The text is closer to the right, not in the middle

**Comment by JustDeimos** [comment]
The text is centered to fit the dialog box.
The size of the dialog box is determined by the size of the text.

You can try using tabs (\t) to expand the dialog box. But not sure if this will work. As a last resort, you can add a long string of some characters and give this string the background color of the dialog box.

**Comment by Pedrilkov** [comment]
Why mock the code like that? I disabled this feature because it does not work and will not work as expected.

**Comment by Pedrilkov** [comment]
Shame!
