### ISSUE TITLE
[IDEA] Expanding functionality in dialog responses

### ISSUE THREAD

**Issue by TommyB123** [Open-GTO/mdialog#4]
Hello there!

I was looking at this include when an idea crossed my mind, but I'm not sure how applicable it is in PAWN. A common hurdle I encounter while handling dialogs is passing temporary data (for example, the playerid of another user) from the context of a command to a dialog. To circumvent this I've created a large multidimensional array which can be used to reference these values. It works just fine of course, but I wondered if it would be possible to pass these values through `Dialog_Open` and reference them in a dialog response, similar to the parameters of `SetTimerEx`.

Example:

```PAWN
new matchescount, matches[MAX_HOUSES], caption[50];

//find any house based on the description provided
foreach(a: Houses)
{
	if(strfind(HouseData[a][HouseDescription], params, true) != -1)
	{
		matches[matchescount] = a;
		matchescount ++;

		strcat(gstr, sprintf("{FF4753}House: {FFFFFF} %s\n", HouseData[a][HouseDescription]));
		if(strlen(gstr) > 1950) break;
	}
}
format(caption, sizeof(caption), "{FBFF00}%i {FFFFFF}possible locations found:", matchescount);
Dialog_Open(playerid, Dialog:NavigationDialog, DIALOG_STYLE_LIST, caption, gstr, "Goto", "Cancel", "si", matches, matchescount);

//dialog response
DialogResponse:NavigationDialog(playerid, response, listitem, inputtext[], houses[])
{
	if(!response) return true;

	if(IsValidDynamicRaceCP(GPSCheckpoint[playerid])) DestroyDynamicRaceCP(GPSCheckpoint[playerid]);

	new a = houses[listitem];
	HasGPSWaypoint[playerid] = 1;
	SendClientMessage(playerid, COLOR_ORANGE, sprintf("Pocket GPS set to '%s'.", description));
	SendSatNavText(playerid, "GPS voice says: Calculating route, please wait...");
	GPSCheckpoint[playerid] = CreateDynamicRaceCP(2, HouseData[a][oPosX], HouseData[a][oPosY], HouseData[a][oPosZ], 0.0, 0.0, 0.0, 20.0, -1, -1, playerid, -1);
	SendSatNavText(playerid, sprintf("GPS voice says: Route to '%s' calculated, proceed to waypoint.", description));
	return true;
}
```

Like I said, I lack the knowledge to know how applicable/possible this would be in PAWN but I figured there would be no harm in suggesting.

**Comment by ziggi** [comment]
This can be realised with additional array, same as yours realization. Or with `#emit` stuff, in which I'm not good. Anyway, this will broke [current integration](https://github.com/Open-GTO/mdialog#zlang-support) with [zlang](https://github.com/Open-GTO/zlang) library.

**Comment by TommyB123** [comment]
Ah, that's a shame. Thanks for considering the idea!
